### ISSUE TITLE
Submitting kanban board

### ISSUE THREAD

**Issue by emarkees** [emarkees/Recipe_App#15]
Link to project:
[Recipe_App](https://github.com/emarkees/Recipe_App/projects/1)

-number of members:
-3

**Comment by codepantha** [comment]
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️The `To Do`, `In Progress`, `In Review`, and `Done` columns have been added to the board 📌 

## Required Changes ♻️
_Check the comments under the review._

- [ ] You have only 1 card in your Kanban board. Please consider the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements) and ensure that each requirement has at least one corresponding card in the Kanban board.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ibizugbe** [comment]
Hi @Team👋🏼👋🏼👋🏼,

![approved](https://github.com/emarkees/Recipe_App/assets/64643995/241334f9-b39e-4508-bf7b-54a655687729)
 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅✅

- [x] The required cards have been updated👍🏼.
- [x] Tasks are fairly assigned amongst group members👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mpa-mxiang** [comment]
Thank you @Ibizugbe for the approval!

**Comment by Ibizugbe** [comment]
Hi @Team👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly note that this project is already approved. I understand it still reflects that there are changes requiredm but this was a mistake on my part. kindly wait patiently as it will be reversed manually on your dashboard within the next 24hrs. you can kindly proceed to work on the next milestones👍🏼.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Olamarx** [comment]
@mpa-mxiang I will approve this as you have resubmitted it but Ennio should make required correction.
